/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wy_study_calldll_Runner */

#ifndef _Included_com_wy_study_calldll_Runner
#define _Included_com_wy_study_calldll_Runner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wy_study_calldll_Runner
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wy_study_calldll_Runner_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
